name: wordpress

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"     # WP Admin → http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"     # phpMyAdmin → http://localhost:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      args:
        # Apollo uses /graphql; Apache vhost proxies this to the wordpress service
        VITE_WORDPRESS_GRAPHQL_URL: /graphql
    container_name: vite_frontend_apache
    restart: always
    depends_on:
      - wordpress
    ports:
      - "5173:80"     # Frontend → http://localhost:5173
    networks:
      - webnet

volumes:
  db_data:
  wordpress_data:

networks:
  webnet:
